module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    CATEGORY_COLLECTION:'category',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    WISHLIST_COLLECTON:'wishlist',
    COUPON_COLLECTION:'coupon',
    CATEGORY_OFFERS:'category_offer',
    BANNER_COLLECTION:'banner'
}